export const ERROR_CODES = {
  // Validation
  VALIDATION_REQUIRED: 'VALIDATION_REQUIRED',
  VALIDATION_INVALID_EMAIL: 'VALIDATION_INVALID_EMAIL',
  VALIDATION_MIN_LENGTH: 'VALIDATION_MIN_LENGTH',
  VALIDATION_MAX_LENGTH: 'VALIDATION_MAX_LENGTH',
  VALIDATION_INVALID_FORMAT: 'VALIDATION_INVALID_FORMAT',
  VALIDATION_INVALID_ENUM: 'VALIDATION_INVALID_ENUM',
  VALIDATION_PASSWORD_MIN_LENGTH: 'VALIDATION_PASSWORD_MIN_LENGTH',
  VALIDATION_PASSWORD_MISMATCH: 'VALIDATION_PASSWORD_MISMATCH',
  VALIDATION_INVALID_INPUT: 'VALIDATION_INVALID_INPUT',

  // Auth
  AUTH_INVALID_CREDENTIALS: 'AUTH_INVALID_CREDENTIALS',

  // Network / HTTP
  NET_BAD_REQUEST: 'NET_BAD_REQUEST',
  NET_TIMEOUT: 'NET_TIMEOUT',
  NET_UNAUTHORIZED: 'NET_UNAUTHORIZED',
  NET_FORBIDDEN: 'NET_FORBIDDEN',
  NET_NOT_FOUND: 'NET_NOT_FOUND',
  NET_CONFLICT: 'NET_CONFLICT',
  NET_PAYLOAD_TOO_LARGE: 'NET_PAYLOAD_TOO_LARGE',
  NET_SERVER_ERROR: 'NET_SERVER_ERROR',

  // Business
  BUSINESS_CONFLICT: 'BUSINESS_CONFLICT',

  // System
  SYS_UNEXPECTED: 'SYS_UNEXPECTED',
} as const

export type ErrorCode = (typeof ERROR_CODES)[keyof typeof ERROR_CODES]

const errorCodeSet = new Set<ErrorCode>(Object.values(ERROR_CODES))

export function isErrorCode(value: unknown): value is ErrorCode {
  return typeof value === 'string' && errorCodeSet.has(value as ErrorCode)
}
